version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: booking_db
    environment:
      POSTGRES_DB: booking_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - booking_network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: booking_redis
    ports:
      - "6379:6379"
    networks:
      - booking_network

volumes:
  postgres_data:

networks:
  booking_network:
    driver: bridge
